import { SyllabusSubject } from './types';

export const ABES_SYLLABUS: SyllabusSubject[] = [
  // =========================================================================
  // SEMESTER III — CORE & ELECTIVE THEORY SUBJECTS (5-UNIT STRUCTURE)
  // =========================================================================
  {
    id: 's-25cs301',
    code: '25CS301',
    name: 'Object Oriented Programming System',
    credits: 3,
    semester: 3,
    category: 'theory',
    electiveTrack: 'Core',
    units: [
      {
        unitNumber: 1,
        unitName: 'Programming Paradigms and C++ Basics',
        topics: [
          'Evolution of programming paradigms',
          'Monolithic, procedural, structured and OOP programming',
          'Structured vs Object Oriented Development',
          'Structure of C++ program',
          'Classes and objects',
          'Scope resolution operator',
          'Reference variables',
          'Functions',
          'Parameter passing: value, reference and address',
          'Inline functions',
          'Function overloading',
          'Default arguments',
          'Variadic functions',
          'auto keyword',
          'Range-based for loop',
        ],
      },
      {
        unitNumber: 2,
        unitName: 'Classes, Objects and Memory Management',
        topics: [
          'Accessing class members',
          'Member functions',
          'Data hiding',
          'Objects as arguments and return values',
          'Friend functions and classes',
          'Constant parameters',
          'Static data and member functions',
          'Constructors and destructors',
          'Constant objects',
          'Nested classes',
          'Pointers to objects',
          'Dynamic object management',
          'Array of objects',
          'this pointer',
          'Self-referential classes',
          'unique_ptr',
          'shared_ptr',
          'nullptr',
        ],
      },
      {
        unitNumber: 3,
        unitName: 'Polymorphism and Operator Overloading',
        topics: [
          'Concept of polymorphism',
          'Compile-time and runtime polymorphism',
          'Function overloading',
          'Function overriding',
          'Constructor overloading and chaining',
          'Operator overloading',
          'Unary and binary operator overloading',
          'Member and friend function operator overloading',
          'Data conversion between basic types and objects',
        ],
      },
      {
        unitNumber: 4,
        unitName: 'Inheritance and Virtual Functions',
        topics: [
          'Concepts of inheritance',
          'Single, multilevel, multiple and hierarchical inheritance',
          'Benefits and cost of inheritance',
          'Composition vs inheritance',
          'Member accessibility',
          'Constructors and destructors in derived classes',
          'Constructor invocation',
          'Data member initialization',
          'Function overriding',
          'Virtual functions',
          'Runtime polymorphism',
          'Base class pointer and derived object',
          'Pure virtual functions',
          'Abstract classes',
          'Virtual destructors',
        ],
      },
      {
        unitNumber: 5,
        unitName: 'Templates and STL',
        topics: [
          'Function templates',
          'Class templates',
          'Function overloading with templates',
          'Generic programming',
          'Standard Template Library',
          'Containers',
          'Iterators',
          'Algorithms',
          'pair',
          'vector',
          'set',
          'map',
          'stack',
          'queue',
          'sort',
          'find',
          'Function objects',
          'Comparators',
          'Lambda expressions',
        ],
      },
    ],
  },
  {
    id: 's-25cs302',
    code: '25CS302',
    name: 'Operating System',
    credits: 3,
    semester: 3,
    category: 'theory',
    electiveTrack: 'Core',
    units: [
      {
        unitNumber: 1,
        unitName: 'Introduction and Process Fundamentals',
        topics: [
          'Operating System overview',
          'Definition, goals and functions',
          'Classification of operating systems',
          'Batch systems',
          'Interactive systems',
          'Time-sharing systems',
          'Real-time systems',
          'Multiprocessor systems',
          'Multiuser systems',
          'Multithreaded systems',
          'Multiprogramming vs multitasking',
          'OS architectures',
          'Kernel mode and user mode',
          'System calls',
          'Layered systems',
          'Monolithic systems',
          'Microkernel systems',
          'Reentrant kernel',
          'Virtual machines',
          'Containers',
          'VM vs Container',
          'Program, process and thread',
          'Process states',
          'Process Control Block (PCB)',
        ],
      },
      {
        unitNumber: 2,
        unitName: 'CPU Scheduling and Deadlock Management',
        topics: [
          'CPU scheduling',
          'CPU-I/O burst cycle',
          'Preemptive and non-preemptive scheduling',
          'Context switching',
          'Schedulers',
          'Dispatcher',
          'Scheduling criteria',
          'FCFS',
          'SJF',
          'SRTF',
          'Priority scheduling',
          'Round Robin',
          'Multilevel Queue',
          'Multilevel Feedback Queue',
          'Real-world scheduling',
          'Deadlock',
          'Deadlock characterization',
          'Deadlock prevention',
          'Deadlock avoidance',
          "Banker's Algorithm",
          'Deadlock detection',
          'Resource Allocation Graph',
          'Wait-for Graph',
          'Deadlock recovery',
          'Starvation vs Deadlock',
        ],
      },
      {
        unitNumber: 3,
        unitName: 'Process Synchronization and Concurrency',
        topics: [
          'Concurrent processes',
          'Principles of concurrency',
          'Race condition',
          'Critical Section Problem',
          "Peterson's Algorithm",
          'Test-and-Set',
          'Mutex locks',
          'Semaphores',
          'Binary and counting semaphores',
          'Inter-Process Communication',
          'Shared memory',
          'Message passing',
          'Producer-Consumer Problem',
          'Dining Philosophers Problem',
          'Sleeping Barber Problem',
          'Concurrent web servers',
          'Thread pools',
          'Request queues',
        ],
      },
      {
        unitNumber: 4,
        unitName: 'Memory Management and Virtual Memory',
        topics: [
          'Logical and physical address space',
          'Address binding',
          'Dynamic loading and linking',
          'Memory protection',
          'Fixed and variable partitioning',
          'Internal and external fragmentation',
          'Compaction',
          'First Fit',
          'Best Fit',
          'Worst Fit',
          'Paging',
          'Page table',
          'Address translation',
          'TLB',
          'Segmentation',
          'Segmentation with paging',
          'Virtual memory',
          'Demand paging',
          'Page fault handling',
          'Locality of reference',
          'Frame allocation',
          'Thrashing',
          'Working Set Model',
        ],
      },
      {
        unitNumber: 5,
        unitName: 'Disk and File System Management',
        topics: [
          'Disk management',
          'Disk structure',
          'Disk performance',
          'FCFS disk scheduling',
          'SSTF',
          'SCAN',
          'C-SCAN',
          'LOOK',
          'C-LOOK',
          'RAID',
          'RAID levels',
          'File systems',
          'File attributes',
          'File operations',
          'File organization',
          'Buffering and caching',
          'Sequential access',
          'Direct access',
          'Directory management',
          'Directory structures',
          'Naming',
          'Searching',
          'Access control',
          'Backups',
          'Journaling file systems',
          'Log-structured file systems',
        ],
      },
    ],
  },
  {
    id: 's-25cs303',
    code: '25CS303',
    name: 'Advanced Data Structure',
    credits: 3,
    semester: 3,
    category: 'theory',
    electiveTrack: 'Core',
    units: [
      {
        unitNumber: 1,
        unitName: 'Stack and Queue',
        topics: [
          'Stack terminology',
          'Stack representation',
          'Array implementation',
          'Linked-list implementation',
          'Push',
          'Pop',
          'Peek',
          'Infix, prefix and postfix',
          'Expression conversion',
          'Expression evaluation',
          'Queue terminology',
          'Linear queue',
          'Circular queue',
          'Deque',
          'Priority queue',
          'Queue representation',
          'Enqueue',
          'Dequeue',
          'Stack and Queue using STL',
        ],
      },
      {
        unitNumber: 2,
        unitName: 'Recursion and Divide & Conquer',
        topics: [
          'Recursion terminology',
          'Direct and indirect recursion',
          'Singly, multiply, tail, non-tail and nested recursion',
          'Recursion optimization',
          'Iteration vs recursion',
          'Recursive problem solving',
          'Divide and Conquer',
          'Merge Sort',
          'Quick Sort',
          'Recurrence relations',
          'Substitution/iteration method',
          'Recursion tree',
          'Master Theorem',
        ],
      },
      {
        unitNumber: 3,
        unitName: 'Trees and Tries',
        topics: [
          'Tree terminology',
          'Tree representation',
          'Complete Binary Tree',
          'Strict Binary Tree',
          'Skewed Binary Tree',
          'Multi-way Tree',
          'Binary Tree',
          'Binary Search Tree',
          'Tree traversal',
          'BFS',
          'DFS',
          'Preorder',
          'Inorder',
          'Postorder',
          'Tree insertion',
          'Tree deletion',
          'Tree searching',
          'Expression Trees',
          'AVL Tree',
          'B-Tree',
          'B+ Tree',
          'Red-Black Tree',
          'Threaded Binary Tree',
          'Height-balanced tree operations',
          'Tries',
          'Trie insertion',
          'Trie search',
          'Prefix search',
        ],
      },
      {
        unitNumber: 4,
        unitName: 'Heap',
        topics: [
          'Heap terminology',
          'Heap representation',
          'Heap property',
          'Max Heap',
          'Min Heap',
          'Building a heap',
          'Heap operations',
          'Maintaining a heap',
          'Heap Sort',
          'Heap as Priority Queue',
          'Priority Queue in STL',
          'Custom comparators',
        ],
      },
      {
        unitNumber: 5,
        unitName: 'Graphs',
        topics: [
          'Graph terminology',
          'Graph representation',
          'Adjacency Matrix',
          'Adjacency List',
          'Directed and undirected graphs',
          'Weighted and unweighted graphs',
          'Cyclic and acyclic graphs',
          'Bipartite graph',
          'Complete graph',
          'DFS',
          'BFS',
          'Connected Components',
          'Cycle Detection',
          'Topological Sorting',
          'DAG',
          'Strongly Connected Components',
          'Articulation Points',
          'Bridges',
          'Bi-connected Components',
        ],
      },
    ],
  },
  {
    id: 's-25va301',
    code: '25VA301',
    name: 'Data Visualization using Python',
    credits: 3,
    semester: 3,
    category: 'theory',
    electiveTrack: 'AI',
    isElective: true,
    units: [
      {
        unitNumber: 1,
        unitName: 'Introduction to Data Visualization and Python',
        topics: [
          'Python basics',
          'Variables',
          'Data types',
          'Operators',
          'Conditional statements',
          'Loops',
          'Functions',
          'Introduction to Data Visualization',
          'Need for Data Visualization',
          'Industry use cases',
          'Human perception',
          'Visual encoding',
          'Types of charts',
          'CSV, JSON and Excel',
          'Jupyter',
          'VS Code',
          'Kaggle',
          'Pandas',
          'NumPy',
          'Exploratory Data Analysis',
        ],
      },
      {
        unitNumber: 2,
        unitName: 'Foundation for Visualization (Matplotlib & Seaborn)',
        topics: [
          'Figure',
          'Axes',
          'Labels',
          'Line plots',
          'Bar charts',
          'Scatter plots',
          'Histograms',
          'Subplots',
          'Layout management',
          'Styling',
          'Annotations',
          'Saving and exporting plots',
          'Exploratory Visualization Workflow',
          'Seaborn',
        ],
      },
      {
        unitNumber: 3,
        unitName: 'Statistical Visualization',
        topics: [
          'Seaborn aesthetics',
          'Categorical plots',
          'Distribution plots',
          'Sampling techniques',
          'Central tendency',
          'Dispersion',
          'Outliers',
          'Pearson correlation',
          'Spearman correlation',
          'Covariance',
          'Box plots',
          'Probability Density Functions',
          'Regression',
          'Folium',
          'Plotly',
        ],
      },
      {
        unitNumber: 4,
        unitName: 'Interactive Visualization (Plotly, Dash & Streamlit)',
        topics: [
          'Interactive visuals',
          'Plotly',
          'Interactive scatter, bar and line charts',
          'Hover',
          'Click',
          'Zoom',
          'Animation',
          'Time-series visualization',
          'Dash',
          'Layouts',
          'Callback functions',
          'Web dashboards',
          'Streamlit',
          'Real-time dashboards',
          'APIs',
          'D3.js',
          'SVG',
          'Web-based visualization',
        ],
      },
      {
        unitNumber: 5,
        unitName: 'Visualization Best Practices and Real Case Studies',
        topics: [
          'Visualization best practices',
          'Visualization ethics',
          'Color theory',
          'Accessibility',
          'Data storytelling',
          'Time-series visualization',
          'Geo-data visualization',
          'Interactive vs static graphs',
          'Power BI',
          'Dashboard design',
          'Portfolio development',
          'GenAI usage',
          'Capstone project',
          'Confusion Matrix',
          'Feature Importance',
          'Streamlit deployment',
          'GitHub deployment',
        ],
      },
    ],
  },
  {
    id: 's-25va302',
    code: '25VA302',
    name: 'Fundamentals of Cloud Computing',
    credits: 3,
    semester: 3,
    category: 'theory',
    electiveTrack: 'Cloud',
    isElective: true,
    units: [
      {
        unitNumber: 1,
        unitName: 'Introduction to Cloud Computing',
        topics: [
          'Evolution of computing',
          'Introduction to cloud computing',
          'Characteristics and benefits',
          'IaaS',
          'PaaS',
          'SaaS',
          'Public cloud',
          'Private cloud',
          'Hybrid cloud',
          'Community cloud',
          'Cloud infrastructure',
          'Compute',
          'Storage',
          'Networking',
          'Major cloud providers',
          'Applications of cloud computing',
        ],
      },
      {
        unitNumber: 2,
        unitName: 'Virtualization and Cloud Management',
        topics: [
          'Virtualization',
          'Types of virtualization',
          'Hypervisors',
          'Virtual machines',
          'Containerization',
          'Resource pooling',
          'Elasticity',
          'Scalability',
          'Cloud resource provisioning',
          'Cloud compute services',
          'Amazon EC2',
          'VM instance management',
          'Cloud cost models',
          'Pricing basics',
        ],
      },
      {
        unitNumber: 3,
        unitName: 'Cloud Networking and Compute Services',
        topics: [
          'Cloud networking',
          'Public and private networks',
          'IP addressing',
          'Subnetting',
          'Routing',
          'Firewalls',
          'DNS',
          'Virtual compute resources',
          'Load balancing',
          'Auto scaling',
          'Cloud monitoring',
          'Amazon VPC',
          'Public and private subnets',
        ],
      },
      {
        unitNumber: 4,
        unitName: 'Cloud Storage and Database Services',
        topics: [
          'Cloud storage',
          'Object storage',
          'Block storage',
          'File storage',
          'Storage selection',
          'Backup and recovery',
          'Amazon S3',
          'Relational databases',
          'NoSQL databases',
          'Data warehousing',
        ],
      },
      {
        unitNumber: 5,
        unitName: 'Cloud Security and Best Practices',
        topics: [
          'Cloud security fundamentals',
          'Shared Responsibility Model',
          'IAM',
          'Authentication',
          'Authorization',
          'Encryption',
          'High availability',
          'Cost optimization',
          'Cloud monitoring',
          'Cloud best practices',
          'Cloud security case studies',
          'Cloud adoption case studies',
        ],
      },
    ],
  },
  {
    id: 's-25as301',
    code: '25AS301',
    name: 'Applied Maths for Computing Applications',
    credits: 4,
    semester: 3,
    category: 'theory',
    electiveTrack: 'Math',
    units: [
      { unitNumber: 1, unitName: 'Discrete Structures & Logic', topics: ['Propositional Logic', 'Predicates & Quantifiers', 'Sets, Relations & Functions', 'Lattices & Boolean Algebra'] },
      { unitNumber: 2, unitName: 'Probability & Statistics', topics: ['Random Variables', 'Probability Distributions', 'Expectation & Variance', 'Bayes Theorem'] },
      { unitNumber: 3, unitName: 'Linear Algebra & Matrices', topics: ['Vector Spaces', 'Eigenvalues & Eigenvectors', 'Matrix Decomposition', 'Orthogonality'] },
      { unitNumber: 4, unitName: 'Combinatorics & Graph Theory', topics: ['Permutations & Combinations', 'Recurrence Relations', 'Generating Functions', 'Graph Isomorphism'] },
      { unitNumber: 5, unitName: 'Numerical Methods for Computing', topics: ['Root Finding Algorithms', 'Numerical Integration', 'Interpolation', 'Finite Differences'] },
    ],
  },
  {
    id: 's-25hu301',
    code: '25HU301',
    name: 'Universal Human Values',
    credits: 3,
    semester: 3,
    category: 'theory',
    electiveTrack: 'Humanities',
    isElective: true,
    units: [
      { unitNumber: 1, unitName: 'Introduction to Value Education', topics: ['Self-Exploration', 'Continuous Happiness and Prosperity', 'Basic Human Aspirations', 'Right Understanding'] },
      { unitNumber: 2, unitName: 'Harmony in the Human Being', topics: ['Understanding Myself', 'Body as an Instrument', 'Health and Self-Regulation', 'Co-existence of Self and Body'] },
      { unitNumber: 3, unitName: 'Harmony in the Family & Society', topics: ['Trust and Respect', 'Foundation of Human Values', 'Justice in Relationships', 'Universal Social Order'] },
      { unitNumber: 4, unitName: 'Harmony in Nature', topics: ['Four Orders of Nature', 'Interconnectedness', 'Self-Regulation in Nature', 'Holistic Perception'] },
      { unitNumber: 5, unitName: 'Holistic Understanding of Harmony', topics: ['Universal Human Order', 'Ethical Human Conduct', 'Holistic Technology & Systems', 'Case Studies'] },
    ],
  },
  {
    id: 's-25hu302',
    code: '25HU302',
    name: 'Technical Communication',
    credits: 2,
    semester: 3,
    category: 'theory',
    electiveTrack: 'Humanities',
    isElective: true,
    alternativeTo: '25HU301',
    notesNotice: 'Detailed unit-wise syllabus not provided in the available booklet',
    units: [
      { unitNumber: 1, unitName: 'Fundamentals of Technical Communication', topics: ['Process of Communication', 'Language as a Tool of Communication', 'Barriers to Communication', 'Professional Communication Etiquette'] },
      { unitNumber: 2, unitName: 'Forms of Technical Communication', topics: ['Technical Report Writing', 'Project Proposals', 'Research Papers', 'Business Correspondence'] },
      { unitNumber: 3, unitName: 'Technical Presentation & Oral Skills', topics: ['Public Speaking', 'Group Discussions', 'Interview Techniques', 'PowerPoint Presentation Design'] },
      { unitNumber: 4, unitName: 'Grammar and Technical Style', topics: ['Sentence Structure', 'Active and Passive Voice in Technical Writing', 'Clarity, Conciseness and Precision', 'Vocabulary Enrichment'] },
      { unitNumber: 5, unitName: 'Digital and Workplace Communication', topics: ['Email Writing Etiquette', 'Technical Documentation', 'Virtual Meetings & Collaboration', 'Cross-Cultural Communication'] },
    ],
  },
  // Semester III Emerging Tech Electives
  {
    id: 's-25va303',
    code: '25VA303',
    name: 'Electronic Circuits using SPICE Modelling',
    credits: 3,
    semester: 3,
    category: 'theory',
    electiveTrack: 'VLSI',
    isElective: true,
    notesNotice: 'Detailed unit-wise syllabus not provided in the available booklet',
  },
  {
    id: 's-25va304',
    code: '25VA304',
    name: 'Basic of Electric Mobility & Vehicle Architecture',
    credits: 3,
    semester: 3,
    category: 'theory',
    electiveTrack: 'EV',
    isElective: true,
    notesNotice: 'Detailed unit-wise syllabus not provided in the available booklet',
  },
  {
    id: 's-25va305',
    code: '25VA305',
    name: 'Industrial Automation using PLC',
    credits: 3,
    semester: 3,
    category: 'theory',
    electiveTrack: 'Industrial Automation',
    isElective: true,
    notesNotice: 'Detailed unit-wise syllabus not provided in the available booklet',
  },
  {
    id: 's-25va306',
    code: '25VA306',
    name: 'Fundamentals of Digital Automotive & Design',
    credits: 3,
    semester: 3,
    category: 'theory',
    electiveTrack: 'Digital Automotive',
    isElective: true,
    notesNotice: 'Detailed unit-wise syllabus not provided in the available booklet',
  },

  // =========================================================================
  // SEMESTER III — PRACTICAL LABS, WORKSHOPS & SKILL COURSES
  // =========================================================================
  {
    id: 's-25cs351',
    code: '25CS351',
    name: 'Object Oriented Programming System Lab',
    credits: 1,
    semester: 3,
    category: 'lab',
    isLab: true,
    experiments: [
      'Experiment 1: Convert procedural student record system into OOP classes and objects',
      'Experiment 2: Demonstrate parameter passing: call by value, call by reference, call by address',
      'Experiment 3: Implement inline functions, default arguments, and function overloading',
      'Experiment 4: Modern C++ features: auto keyword and range-based for loops',
      'Experiment 5: Design a bank account class with data hiding, deposit and withdrawal',
      'Experiment 6: Constructors (default, parameterized, copy) and destructor lifecycle',
      'Experiment 7: Implement static data members, static functions and friend functions',
      'Experiment 8: Passing objects as arguments and returning objects from functions',
      'Experiment 9: Pointers to objects, array of objects and dynamic memory allocation',
      'Experiment 10: Smart pointers (unique_ptr, shared_ptr) for safe memory management',
      'Experiment 11: Function overloading for arithmetic operations on varied data types',
      'Experiment 12: Overload unary and binary operators (e.g. Complex numbers class)',
      'Experiment 13: Type conversion between basic data types and user-defined classes',
      'Experiment 14: Single and multilevel inheritance implementation with real-world hierarchy',
      'Experiment 15: Function overriding and scope resolution in derived classes',
      'Experiment 16: Virtual functions, vtables and runtime polymorphism with base class pointers',
      'Experiment 17: Abstract classes and pure virtual functions with concrete derived implementations',
      'Experiment 18: Object composition vs inheritance-based architecture comparison',
      'Experiment 19: Function template for generic operations (generic swapping and sorting)',
      'Experiment 20: Class template for generic Stack and Queue data structures',
      'Value Added Exp 21: STL vector and iterators to store and process collection of elements',
      'Value Added Exp 22: STL map and set for key-value pair and unique element storage',
      'Value Added Exp 23: STL algorithms library usage (std::sort, std::find, std::transform)',
      'Value Added Exp 24: Lambda expressions for customized comparator sorting and filtering',
    ],
    vivaTopics: ['Virtual Destructors', 'Diamond Problem in Multiple Inheritance', 'vtable & vptr Internals', 'Smart Pointers in C++11', 'RAII Pattern'],
  },
  {
    id: 's-25cs352',
    code: '25CS352',
    name: 'Operating System Lab',
    credits: 1,
    semester: 3,
    category: 'lab',
    isLab: true,
    experiments: [
      'Experiment 1: Study OS requirements (Windows/Linux/Unix) and execute DOS/shell commands',
      'Experiment 2: Linux Shell Scripting with conditionals, loops and environment variables',
      'Experiment 3: Process and Thread creation and control using fork(), pthread_create(), pthread_join()',
      'Experiment 4: Implement FCFS (First Come First Serve) CPU Scheduling Algorithm',
      'Experiment 5: Implement SJF (Shortest Job First) CPU Scheduling Algorithm',
      'Experiment 6: Implement SRTF (Shortest Remaining Time First) CPU Scheduling Algorithm',
      'Experiment 7: Implement Priority Scheduling Algorithm (Preemptive and Non-preemptive)',
      'Experiment 8: Implement Round Robin CPU Scheduling Algorithm with time quantum',
      "Experiment 9: Simulate Banker's Algorithm for Deadlock Avoidance and Safety State",
      'Experiment 10: Simulate memory allocation & fragmentation (First Fit, Best Fit, Worst Fit)',
      'Value Added Exp 11: Simulate FIFO (First In First Out) Page Replacement Algorithm',
      'Value Added Exp 12: Simulate LRU (Least Recently Used) Page Replacement Algorithm',
    ],
    vivaTopics: ['Context Switching Overhead', 'Zombie vs Orphan Processes', 'Thrashing Prevention', 'Peterson Algorithm Proof', 'Demand Paging'],
  },
  {
    id: 's-25cs353',
    code: '25CS353',
    name: 'Advanced Data Structure Lab',
    credits: 1,
    semester: 3,
    category: 'lab',
    isLab: true,
    experiments: [
      'Experiment 1: Stack and Queue Applications (Infix to Postfix conversion, Circular Queue)',
      'Experiment 2: Binary Search Tree (Insertion, Deletion, DFS & BFS Traversals)',
      'Experiment 3: AVL Tree Rotations and Height-Balanced Tree Operations',
      'Experiment 4: Trie Data Structure for Fast Prefix and Dictionary Word Search',
      'Experiment 5: Min Heap & Max Heap Construction and Heap Sort Algorithm',
      'Experiment 6: Graph Representations (Matrix & List), BFS, DFS, and Cycle Detection',
      'Experiment 7: Topological Sorting and Strongly Connected Components (Kosaraju)',
      "Experiment 8: Disjoint Set Union (DSU) and Kruskal's Minimum Spanning Tree Algorithm",
    ],
    vivaTopics: ['AVL Tree Rebalancing', 'Trie vs Hash Map Complexity', 'Red-Black Tree Properties', 'Amortized DSU Analysis'],
  },
  {
    id: 's-25va351',
    code: '25VA351',
    name: 'FSD Workshop-I',
    credits: 1,
    semester: 3,
    category: 'workshop',
    isLab: true,
    experiments: [
      'Experiment 1: Node.js Events, EventEmitter, and Event Loop (setTimeout, setImmediate, nextTick)',
      'Experiment 2: File System Operations using Node.js (fs module CRUD on files)',
      'Experiment 3: Basic HTTP Server using http.createServer() with status codes and headers',
      'Experiment 4: Basic GraphQL API development with express-graphql',
      'Experiment 5: Node.js HTTP Routing (GET, POST, PUT, DELETE)',
      'Experiment 6: Express.js Server serving static HTML pages across routes (/ , /about, /contact)',
      'Experiment 7: MongoDB Setup locally/Atlas (Database: studentDB, Collection: students)',
      'Experiment 8: MongoDB CRUD Operations (Insert 5 records, $set age update, queries, delete)',
      'Experiment 9: REST API Development using Express and MongoDB (/students CRUD endpoints)',
      'Experiment 10: GitHub Project Deployment (Clean folder structure, README.md, .gitignore)',
      'Value Added Exp 11: Dockerize Node.js + MongoDB Application (Dockerfile, image build & run)',
      'Value Added Exp 12: Student Management System (React + Express + MongoDB, Dockerized on Render)',
    ],
    vivaTopics: ['Node.js Event Loop Phases', 'Mongoose ODM vs Native Driver', 'Microservices with Docker', 'REST vs GraphQL'],
  },
  {
    id: 's-25va309',
    code: '25VA309',
    name: 'Employability Skills',
    credits: 1,
    semester: 3,
    category: 'skill',
    skillCategories: [
      { categoryName: 'Logical Reasoning', tasks: ['Deductive Reasoning', 'Blood Relations', 'Seating Arrangements', 'Coding-Decoding', 'Syllogism'] },
      { categoryName: 'Quantitative Aptitude', tasks: ['Percentages and Profit/Loss', 'Time, Speed and Distance', 'Permutations & Combinations', 'Data Interpretation'] },
      { categoryName: 'Verbal Ability & Aptitude', tasks: ['Reading Comprehension', 'Sentence Correction', 'Para Jumbles', 'Vocabulary & Synonyms'] },
      { categoryName: 'Employability & Soft Skills', tasks: ['Resume Building', 'Group Discussion Dynamics', 'Email and Workplace Etiquette', 'Elevator Pitch Practice'] },
    ],
  },
  {
    id: 's-25va352',
    code: '25VA352',
    name: 'Holistic Skill & Innovation III',
    credits: 1,
    semester: 3,
    category: 'innovation',
    skillCategories: [
      { categoryName: 'Innovation & Problem Solving', tasks: ['Design Thinking Workshop', 'Ideation & Prototyping', 'Real-World Problem Identification'] },
      { categoryName: 'Entrepreneurship & Startup Skills', tasks: ['Business Model Canvas (BMC)', 'Pitch Deck Preparation', 'Market Research & Validation'] },
      { categoryName: 'Industry Connect & Expert Sessions', tasks: ['Tech Talks with Industry Mentors', 'Industrial Case Studies', 'Alumni Mentorship Connect'] },
      { categoryName: 'Activities & Participation', tasks: ['Hackathon Participation', 'Mini Project Showcase', 'Peer Code Reviews & Feedback'] },
    ],
  },

  // =========================================================================
  // SEMESTER IV — CORE & ELECTIVE THEORY SUBJECTS (5-UNIT STRUCTURE)
  // =========================================================================
  {
    id: 's-25cs401',
    code: '25CS401',
    name: 'Computer Organization and Architecture',
    credits: 3,
    semester: 4,
    category: 'theory',
    electiveTrack: 'Core',
    units: [
      {
        unitNumber: 1,
        unitName: 'Introduction & Machine Instructions',
        topics: [
          'Von Neumann architecture',
          'Harvard architecture',
          'Basic computer system',
          'Functional units',
          'Bus',
          'Types of bus',
          'Multiplexer',
          'Decoder',
          'Tri-state buffer',
          'Registers',
          'General register organization',
          'Instruction format',
          'Addressing modes',
          '8085 architecture',
        ],
      },
      {
        unitNumber: 2,
        unitName: 'Arithmetic Logic Unit (ALU)',
        topics: [
          'Number systems',
          'Carry look-ahead adders',
          "Booth's Algorithm",
          'Restoring division algorithm',
          'Floating-point arithmetic',
          'ALU design',
          'IEEE floating-point standard',
        ],
      },
      {
        unitNumber: 3,
        unitName: 'Control Unit & Instruction Pipelining',
        topics: [
          'Instruction cycle',
          'Pipelining',
          'RISC',
          'CISC',
          'Hard-wired control unit',
          'Micro-programmed control unit',
          'GPU architecture',
          'NPU',
          'GPU vs CPU architecture',
        ],
      },
      {
        unitNumber: 4,
        unitName: 'Memory Organization & Cache Memory',
        topics: [
          'Memory organization',
          'Memory hierarchy',
          'Memory interleaving',
          'Cache coherence',
          'Cache memory',
          'Cache size vs block size',
          'Direct mapping',
          'Fully associative mapping',
          'Set associative mapping',
          'LRU',
          'FIFO',
          'LFU',
          'Write-through',
          'Write-back',
        ],
      },
      {
        unitNumber: 5,
        unitName: 'I/O Organization and Multiprocessors',
        topics: [
          'Peripheral devices',
          'I/O interface',
          'I/O ports',
          'Interrupts',
          'Interrupt hardware',
          'Interrupt types',
          'Exceptions',
          'Programmed I/O',
          'Interrupt initiated I/O',
          'DMA',
          'I/O channels',
          'I/O processors',
          "Flynn's classification",
          'SISD',
          'SIMD',
          'MISD',
          'MIMD',
          'Array processors',
          'Interconnection architecture',
          'Arbitration',
        ],
      },
    ],
  },
  {
    id: 's-25cs402',
    code: '25CS402',
    name: 'Database Management System',
    credits: 3,
    semester: 4,
    category: 'theory',
    electiveTrack: 'Core',
    units: [
      {
        unitNumber: 1,
        unitName: 'Introduction to Database and ER Modeling',
        topics: [
          'Data vs Information',
          'Database',
          'DBMS',
          'File System vs DBMS',
          'Instances and Schemas',
          'Three-Schema Architecture',
          'Data Independence',
          'Data Models',
          'Database languages',
          'Database architecture',
          'ER Model',
          'Entities',
          'Entity Sets',
          'Attributes',
          'Strong and weak entities',
          'Relationships',
          'Mapping cardinalities',
          'Participation constraints',
          'Super Key',
          'Candidate Key',
          'Primary Key',
          'Alternate Key',
          'Foreign Key',
          'Generalization',
          'Specialization',
          'Aggregation',
          'ER to relational model',
        ],
      },
      {
        unitNumber: 2,
        unitName: 'Relational Data Model and Relational Algebra',
        topics: [
          'Relational data model',
          'Domains',
          'Tuples',
          'Relations',
          'Entity integrity',
          'Referential integrity',
          'Domain integrity',
          'Procedural query language',
          'Non-procedural query language',
          'Select',
          'Project',
          'Union',
          'Intersection',
          'Difference',
          'Cartesian Product',
          'Rename',
          'Joins',
          'Division',
          'Assignment',
          'Generalized projection',
          'Aggregate functions',
        ],
      },
      {
        unitNumber: 3,
        unitName: 'Structured Query Language (SQL)',
        topics: [
          'SQL data types',
          'DDL',
          'DML',
          'DCL',
          'TCL',
          'CREATE',
          'ALTER',
          'DROP',
          'TRUNCATE',
          'RENAME',
          'SELECT',
          'FROM',
          'WHERE',
          'String operators',
          'ORDER BY',
          'INSERT',
          'UPDATE',
          'DELETE',
          'UNION',
          'UNION ALL',
          'INTERSECT',
          'MINUS',
          'Aggregate functions',
          'NULL values',
          'Subqueries',
          'Nested queries',
          'Correlated queries',
          'GROUP BY',
          'HAVING',
          'Inner Join',
          'Left Outer Join',
          'Right Outer Join',
          'Full Outer Join',
          'Self Join',
          'Natural Join',
          'ON',
          'USING',
        ],
      },
      {
        unitNumber: 4,
        unitName: 'Database Design and Normalization',
        topics: [
          'Functional Dependencies',
          'Trivial and non-trivial dependencies',
          'Transitive dependency',
          'Multivalued dependency',
          "Armstrong's Axioms",
          'Attribute closure',
          'Candidate keys',
          'Canonical cover',
          'Insertion anomaly',
          'Update anomaly',
          'Deletion anomaly',
          '1NF',
          '2NF',
          '3NF',
          'BCNF',
          'Lossless decomposition',
          'Dependency preservation',
          '4NF',
          '5NF',
        ],
      },
      {
        unitNumber: 5,
        unitName: 'Transaction and Concurrency Control',
        topics: [
          'Transactions',
          'ACID properties',
          'Transaction states',
          'Concurrent execution',
          'Serializability',
          'Conflict serializability',
          'View serializability',
          'Precedence graph',
          'Topological sorting',
          'Two-phase locking',
          'Timestamp protocols',
          'Deadlock handling',
          'Recoverability',
          'Recoverable schedules',
          'Cascadeless schedules',
          'Log-based recovery',
          'Deferred database modification',
          'Immediate database modification',
          'Checkpoints',
        ],
      },
    ],
  },
  {
    id: 's-25cs403',
    code: '25CS403',
    name: 'Design and Analysis of Algorithm',
    credits: 3,
    semester: 4,
    category: 'theory',
    electiveTrack: 'Core',
    units: [
      {
        unitNumber: 1,
        unitName: 'Sliding Window and Range Techniques',
        topics: [
          'Fixed-size sliding window',
          'Window sum and average',
          'Frequency/counting problems',
          'Maximum/minimum in a range',
          'Variable-size sliding window',
          'Longest window problems',
          'Shortest window problems',
          'Distinct element problems',
          'Constraint-based subarray and substring problems',
          'Window counting',
          'Hash Map',
          'Hash Set',
        ],
      },
      {
        unitNumber: 2,
        unitName: 'Prefix Sum and Two Pointers',
        topics: [
          'Prefix Sum',
          'Cumulative sums',
          'Precomputation',
          'Prefix sum patterns',
          'Auxiliary data structures',
          'Multidimensional prefix sums',
          'Two Pointers',
          'Same-direction pointers',
          'Opposite-direction pointers',
          'Fast and slow pointers',
        ],
      },
      {
        unitNumber: 3,
        unitName: 'Greedy Approach and Graph Algorithms',
        topics: [
          'Greedy approach',
          'Greedy choice property',
          'Sorting and interval problems',
          'Resource allocation',
          'Priority queue',
          'Disjoint Set Union',
          'Union-Find',
          'Minimum Spanning Tree',
          "Kruskal's Algorithm",
          "Prim's Algorithm",
          "Dijkstra's Algorithm",
        ],
      },
      {
        unitNumber: 4,
        unitName: 'Backtracking Approach',
        topics: [
          'Backtracking',
          'State-space tree',
          'State-space tree pruning',
          'Complexity analysis',
          'Binary choice problems',
          'Multiple-choice problems',
          'Permutation problems',
          'Grid-based problems',
        ],
      },
      {
        unitNumber: 5,
        unitName: 'Dynamic Programming',
        topics: [
          'Dynamic Programming',
          'Overlapping subproblems',
          'Optimal substructure',
          'Memoization',
          'Tabulation',
          'Space optimization',
          'Binary choice problems',
          'Multiple-choice problems',
          'Permutation problems',
          'Grid-based problems',
          'Dynamic Programming on Trees',
          'Dynamic Programming on Graphs',
          'Bellman-Ford',
          'Floyd-Warshall',
          'Travelling Salesman Problem',
        ],
      },
    ],
  },
  {
    id: 's-25va401',
    code: '25VA401',
    name: 'Data Handling and Artificial Intelligence',
    credits: 3,
    semester: 4,
    category: 'theory',
    electiveTrack: 'AI',
    isElective: true,
    units: [
      {
        unitNumber: 1,
        unitName: 'Introduction to Data Handling and Pipelines',
        topics: [
          'Data lifecycle',
          'Structured and unstructured data',
          'Data sources',
          'Data quality',
          'Data cleaning',
          'Files',
          'RDBMS',
          'NoSQL',
          'Data ingestion',
          'ETL',
          'IDE',
          'Data wrangling',
          'Missing values',
          'Outliers',
          'Scaling',
          'Normalization',
          'Big Data ecosystem',
        ],
      },
      {
        unitNumber: 2,
        unitName: 'Data Handling Techniques for AI',
        topics: [
          'Feature engineering',
          'Feature selection',
          'Hypothesis testing',
          'Categorical data',
          'Text data',
          'Encoding',
          'PCA',
          'Time series',
          'Sequence handling',
          'Data pipelines',
          'Workflow automation',
          'Data versioning',
          'Data provenance',
          'SQL for AI',
          'MongoDB',
          'Snowflake',
          'Databricks',
        ],
      },
      {
        unitNumber: 3,
        unitName: 'Fundamentals of AI and Machine Learning',
        topics: [
          'AI vs Machine Learning vs Deep Learning',
          'Supervised learning',
          'Unsupervised learning',
          'Linear Regression',
          'Logistic Regression',
          'KNN',
          'Decision Trees',
          'Random Forest',
          'Accuracy',
          'Precision',
          'Recall',
          'MAE',
          'RMSE',
          'R² score',
          'Bias',
          'Overfitting',
          'Underfitting',
          'Cross-validation',
        ],
      },
      {
        unitNumber: 4,
        unitName: 'Advanced AI Techniques and Neural Networks',
        topics: [
          'Ensemble methods',
          'Bagging',
          'Boosting',
          'Support Vector Machines',
          'Kernel methods',
          'Neural Networks',
          'Perceptron',
          'MLP',
          'Model tuning',
          'Hyperparameter optimization',
          'Cloud-based ML',
          'AWS/Azure',
          'TensorFlow',
          'PyTorch',
          'Ethics and bias',
          'AI model deployment',
        ],
      },
      {
        unitNumber: 5,
        unitName: 'Data Visualization, Interpretation and Industry Trends',
        topics: [
          'Connecting data sources',
          'Dashboarding',
          'Power BI',
          'Tableau',
          'Spatial data visualization',
          'Predictive analysis',
          'Forecasting',
          'Model interpretation',
          'Explainable AI',
          'SHAP',
          'LIME',
          'MLOps',
          'AutoML',
          'Dataiku',
          'Apache Airflow',
          'Project presentation',
          'Reporting',
        ],
      },
    ],
  },
  {
    id: 's-25va402',
    code: '25VA402',
    name: 'Design and Development of Cloud Services',
    credits: 3,
    semester: 4,
    category: 'theory',
    electiveTrack: 'Cloud',
    isElective: true,
    units: [
      {
        unitNumber: 1,
        unitName: 'Introduction to Cloud Architecture',
        topics: [
          'Cloud architecture principles',
          'Cloud reference architecture',
          'Cloud design patterns',
          'Scalability',
          'Elasticity',
          'High availability',
          'Fault tolerance',
          'Cloud-native applications',
          'Monolithic architecture',
          'Microservices architecture',
          'Event-driven architecture',
          'RESTful services',
          'Cloud application design',
        ],
      },
      {
        unitNumber: 2,
        unitName: 'Containerization and Cloud Computing Technologies',
        topics: [
          'Containerization',
          'Docker architecture',
          'Docker images',
          'Docker containers',
          'Container lifecycle',
          'Container orchestration',
          'Kubernetes',
          'Serverless computing',
          'Infrastructure as Code',
          'AWS Management Console',
        ],
      },
      {
        unitNumber: 3,
        unitName: 'Advanced Cloud Networking and DevOps',
        topics: [
          'Virtual networking',
          'Software Defined Networking',
          'Network security',
          'Load balancing',
          'CDN',
          'API management',
          'DevOps',
          'Continuous Integration',
          'Continuous Delivery',
          'Version Control Systems',
        ],
      },
      {
        unitNumber: 4,
        unitName: 'Cloud Data Management and Security',
        topics: [
          'Cloud database services',
          'Distributed databases',
          'Data lakes',
          'Cloud data analytics',
          'Data migration',
          'Backup and disaster recovery',
          'IAM',
          'Authentication',
          'Authorization',
          'Encryption',
          'Monitoring',
          'Logging',
          'Auditing',
          'Amazon S3',
        ],
      },
      {
        unitNumber: 5,
        unitName: 'Cloud Migration, Governance and Emerging Trends',
        topics: [
          'Cloud migration strategies',
          'Cloud cost optimization',
          'Resource monitoring',
          'Cloud governance',
          'Compliance',
          'Multi-cloud',
          'Hybrid cloud',
          'Edge computing',
          'IoT and cloud integration',
          'AI and ML on cloud',
          'Industry case studies',
          'Amazon EC2',
        ],
      },
    ],
  },
  {
    id: 's-25as401',
    code: '25AS401',
    name: 'Applied Maths for Computing Applications (SBE)',
    credits: 4,
    semester: 4,
    category: 'theory',
    electiveTrack: 'Math',
    isElective: true,
    units: [
      { unitNumber: 1, unitName: 'Advanced Calculus & Transforms', topics: ['Laplace Transforms', 'Fourier Series & Transforms', 'Z-Transforms', 'Applications to Signal Processing'] },
      { unitNumber: 2, unitName: 'Probability Theory & Stochastic Processes', topics: ['Markov Chains', 'Poisson Processes', 'Queuing Models', 'Continuous Time Markov Chains'] },
      { unitNumber: 3, unitName: 'Optimization Techniques', topics: ['Linear Programming (Simplex)', 'Duality Theory', 'Integer Programming', 'Non-linear Optimization Basics'] },
      { unitNumber: 4, unitName: 'Information Theory & Coding', topics: ['Entropy and Mutual Information', 'Channel Capacity', 'Huffman and Shannon-Fano Coding', 'Error-Correcting Codes'] },
      { unitNumber: 5, unitName: 'Computational Statistics & Data Analysis', topics: ['Hypothesis Testing (t-test, chi-square)', 'ANOVA', 'Confidence Intervals', 'Monte Carlo Simulation'] },
    ],
  },
  {
    id: 's-25hu401',
    code: '25HU401',
    name: 'Universal Human Values II',
    credits: 3,
    semester: 4,
    category: 'theory',
    electiveTrack: 'Humanities',
    isElective: true,
    units: [
      { unitNumber: 1, unitName: 'Harmony in Existence', topics: ['Holistic Perspective', 'Human Values Overview', 'Right Understanding Evolution', 'Co-existence Principle'] },
      { unitNumber: 2, unitName: 'Self Exploration & Professional Ethics', topics: ['Definitiveness of Ethical Human Conduct', 'Competence in Professional Ethics', 'Issues in Professional Ethics', 'Vision for Holistic Society'] },
      { unitNumber: 3, unitName: 'Holistic Technologies & Systems', topics: ['Eco-Friendly Systems', 'Sustainable Development', 'Humanistic Education', 'Universal Human Order Strategy'] },
      { unitNumber: 4, unitName: 'Humanistic Management & Social Orders', topics: ['Mutually Enriching Human Orders', 'Global Peace & Harmony', 'Transition from Present State', 'Case Studies'] },
      { unitNumber: 5, unitName: 'Implementation Roadmap', topics: ['Personal Transformation', 'Family Order Integration', 'Societal Transition Steps', 'Concluding Evaluation'] },
    ],
  },
  {
    id: 's-25hu402',
    code: '25HU402',
    name: 'Technical Communication II',
    credits: 2,
    semester: 4,
    category: 'theory',
    electiveTrack: 'Humanities',
    isElective: true,
    alternativeTo: '25HU401',
    notesNotice: 'Detailed unit-wise syllabus not provided in the available booklet',
  },
  // Semester IV Emerging Tech Electives
  {
    id: 's-25va403',
    code: '25VA403',
    name: 'VLSI System Design using Verilog and FPGA',
    credits: 3,
    semester: 4,
    category: 'theory',
    electiveTrack: 'VLSI',
    isElective: true,
    notesNotice: 'Detailed unit-wise syllabus not provided in the available booklet',
  },
  {
    id: 's-25va404',
    code: '25VA404',
    name: 'Vehicle Dynamics and EV Power Requirements',
    credits: 3,
    semester: 4,
    category: 'theory',
    electiveTrack: 'EV',
    isElective: true,
    notesNotice: 'Detailed unit-wise syllabus not provided in the available booklet',
  },
  {
    id: 's-25va405',
    code: '25VA405',
    name: 'Industrial Automation based on Pneumatics',
    credits: 3,
    semester: 4,
    category: 'theory',
    electiveTrack: 'Industrial Automation',
    isElective: true,
    notesNotice: 'Detailed unit-wise syllabus not provided in the available booklet',
  },
  {
    id: 's-25va406',
    code: '25VA406',
    name: 'Automotive Product Design and Development',
    credits: 3,
    semester: 4,
    category: 'theory',
    electiveTrack: 'Digital Automotive',
    isElective: true,
    notesNotice: 'Detailed unit-wise syllabus not provided in the available booklet',
  },

  // =========================================================================
  // SEMESTER IV — PRACTICAL LABS, WORKSHOPS & SKILL COURSES
  // =========================================================================
  {
    id: 's-25cs451',
    code: '25CS451',
    name: 'Computer Organization & Architecture Lab',
    credits: 1,
    semester: 4,
    category: 'lab',
    isLab: true,
    experiments: [
      'Experiment 1: Implement the 3-to-8 line Decoder using logic gates',
      'Experiment 2: Simulate 4x1 Multiplexer and verify truth table',
      'Experiment 3: Analyze Binary to Gray and Gray to Binary code conversion circuits',
      'Experiment 4: Design Binary to BCD converter and BCD to Binary converter',
      'Experiment 5: Implement Half Adder and Full Adder using basic logic gates',
      'Experiment 6: Simulate 4-bit Ripple Carry Adder circuit',
      'Experiment 7: Simulate Carry Look Ahead Adder for high-speed arithmetic',
      'Experiment 8: Verify excitation tables of SR and D flip-flops',
      'Experiment 9: Verify excitation tables of JK and T flip-flops',
      'Experiment 10: Implement Half Subtractor and Full Subtractor using logic gates',
      'Value Added Exp 11: Design and simulate a 1-bit Arithmetic Logic Unit (ALU)',
      'Value Added Exp 12: Simulate magnitude comparator of 4-bit binary numbers',
    ],
    vivaTopics: ['Decoder vs Demultiplexer', 'Flip-Flop Excitation Tables', 'ALU Design Tradeoffs', 'Ripple Carry vs Look-Ahead Delay'],
  },
  {
    id: 's-25cs452',
    code: '25CS452',
    name: 'Database Management System Lab',
    credits: 1,
    semester: 4,
    category: 'lab',
    isLab: true,
    experiments: [
      'Experiment 1: Creating ER Diagram using modern Case Tools',
      'Experiment 2: Reduction of ER Diagram into Relational Schema and Foreign Key mappings',
      'Experiment 3: Execution of DDL Commands (CREATE, ALTER, DROP, TRUNCATE) and Integrity Constraints',
      'Experiment 4: Execution of DML Commands (INSERT, UPDATE, DELETE) on relational tables',
      'Experiment 5: Execution of DQL Commands (SELECT, WHERE, LIKE, BETWEEN, ORDER BY)',
      'Experiment 6: Implementation of Nested, Correlated Subqueries and Set Operations',
      'Experiment 7: Implementation of Complex Joins (INNER, LEFT, RIGHT, FULL, NATURAL, SELF)',
      'Experiment 8: Execution of GROUP BY, HAVING, and Aggregate Functions (COUNT, SUM, AVG, MAX, MIN)',
      'Experiment 9: Execution and Management of Database Views and Indexes',
      'Experiment 10: Mini Project: Design and Development of Full-Stack Database Application',
    ],
    vivaTopics: ['ACID Properties Verification', 'Clustered vs Non-Clustered Indexes', 'View Materialization', 'BCNF Decomposition'],
  },
  {
    id: 's-25cs453',
    code: '25CS453',
    name: 'Design & Analysis of Algorithm Lab',
    credits: 1,
    semester: 4,
    category: 'lab',
    isLab: true,
    experiments: [
      'Experiment 1: Sliding Window (Count anagram occurrences, longest substring with at most K distinct chars)',
      'Experiment 2: Minimum Window Substring (Find smallest substring containing all characters of another string)',
      'Experiment 3: Prefix Sum (Count subarrays with equal number of 0s and 1s, max frequency over ranges)',
      'Experiment 4: Two Pointers / Array Problems (Find unique quadruplets, 4-Sum target problem)',
      'Experiment 5: Greedy Approach (Activity Selection problem, maximum non-overlapping intervals)',
      'Experiment 6: Greedy Graph Algorithms (Min cost to connect points via Manhattan distance, Flight routes with K stops)',
      'Experiment 7: Backtracking (Generate unique subsets, Palindrome partitioning)',
      'Experiment 8: Backtracking (N-Queens problem on N x N chessboard, all valid queen configurations)',
      'Experiment 9: Dynamic Programming (Minimum Cost Climbing Stairs, Longest Common Subsequence)',
      'Experiment 10: Dynamic Programming / Graph (Shortest path visiting every node in connected graph)',
      'Value Added Exp 11: Text Analysis Program (Smallest window with keyword characters, distinct count)',
      'Value Added Exp 12: Route Planning System (Minimum-cost travel between cities with at most K stops, MST visualization)',
    ],
    vivaTopics: ['Sliding Window Complexity', 'Memoization vs Tabulation', 'Backtracking State Pruning', 'Kruskal vs Prim MST'],
  },
  {
    id: 's-25va451',
    code: '25VA451',
    name: 'FSD Workshop-II',
    credits: 1,
    semester: 4,
    category: 'workshop',
    isLab: true,
    modules: [
      {
        moduleNumber: 1,
        title: 'Docker and Kubernetes Deployment',
        tasks: [
          'Install Docker on local development machine',
          'Install Kubernetes locally using Minikube or K3s',
          'Create Dockerfile for full-stack Node.js application',
          'Build Docker image and test container execution locally',
          'Create Kubernetes Pod and Service configurations',
          'Write and apply Kubernetes YAML deployment manifests',
        ],
      },
      {
        moduleNumber: 2,
        title: 'Generative AI Integration',
        tasks: [
          'Research 3 real-world Generative AI industry use cases',
          'Build simple text generation tool using OpenAI or Hugging Face APIs',
          'Explore AI code generation using GitHub Copilot / ChatGPT',
          'Document reflections on GenAI prompt engineering and code review',
          'Submit mini-blog and working prototype source code',
        ],
      },
      {
        moduleNumber: 3,
        title: 'CI/CD Pipelines using GitHub Actions',
        tasks: [
          'Create GitHub repository with clean application structure',
          'Configure GitHub Actions workflow for automated test runs on push',
          'Automate Docker image builds via GitHub Actions',
          'Deploy application automatically to Render / Railway',
          'Submit repository link and active CI/CD workflow screenshot',
        ],
      },
      {
        moduleNumber: 4,
        title: 'Project Planning and System Design',
        tasks: [
          'Submit team details, project charter and problem statement',
          'Develop system architecture diagram and GitHub Projects board',
          'Detailed system design: REST API contracts and database schema ERD',
          'Assign module milestones and implement minimum 3 backend API endpoints',
        ],
      },
      {
        moduleNumber: 5,
        title: 'Full-Stack Containerized Application',
        tasks: [
          'Configure database connections and data layer',
          'Dockerize backend service and publish image to DockerHub',
          'Build frontend client and connect to backend container APIs',
          'Deploy locally using Kubernetes (minimum 1 service + 1 pod)',
          'Submit deployment screenshots and code repository',
        ],
      },
      {
        moduleNumber: 6,
        title: 'GenAI + DevOps (Value Added)',
        tasks: [
          'Integrate conversational AI or content generator component',
          'Connect OpenAI / Hugging Face endpoints with validation tests',
          'Automate staging deployment via GitHub Actions workflow YAML',
          'Submit live application staging link and pipeline report',
        ],
      },
      {
        moduleNumber: 7,
        title: 'Cloud Deployment, Monitoring & Capstone (Value Added)',
        tasks: [
          'Deploy complete production system on cloud infrastructure',
          'Add monitoring dashboard with Grafana or structured logging',
          'Perform usability and load testing with Postman / JMeter',
          'Prepare installation guide, user manual, and final video demo',
        ],
      },
    ],
  },
  {
    id: 's-25va409',
    code: '25VA409',
    name: 'Employability Skills II',
    credits: 1,
    semester: 4,
    category: 'skill',
    skillCategories: [
      { categoryName: 'Advanced Logical Reasoning', tasks: ['Critical Thinking', 'Statement & Assumptions', 'Data Sufficiency', 'Cause and Effect'] },
      { categoryName: 'Advanced Quantitative Aptitude', tasks: ['Probability & Permutations in Interviews', 'Mixtures & Alligations', 'Advanced Mensuration & Geometry'] },
      { categoryName: 'Corporate Interview Preparation', tasks: ['Technical Mock Interviews', 'HR Behavioral STAR Method', 'Domain-Specific Interview Questions'] },
      { categoryName: 'Career & Industry Readiness', tasks: ['LinkedIn Profile Optimization', 'Technical Portfolio Design', 'Salary Negotiation & Offer Assessment'] },
    ],
  },
  {
    id: 's-25va452',
    code: '25VA452',
    name: 'Holistic Skill & Innovation IV',
    credits: 1,
    semester: 4,
    category: 'innovation',
    skillCategories: [
      { categoryName: 'Advanced Innovation & Patenting', tasks: ['Intellectual Property Rights (IPR) Basics', 'Provisional Patent Drafting', 'Novelty Analysis'] },
      { categoryName: 'Venture Creation & Funding', tasks: ['Startup Funding Stages (Angel, VC, Grants)', 'Financial Projections & Unit Economics', 'Startup Pitching'] },
      { categoryName: 'Corporate Social Responsibility & Ethics', tasks: ['Community Impact Projects', 'Sustainable Engineering Solutions', 'Ethics in Engineering'] },
      { categoryName: 'Capstone Project Participation', tasks: ['Interdisciplinary Hackathons', 'Industry Sponsored Project Showcase', 'Certification Submission'] },
    ],
  },
];

// Helper to look up subject syllabus
export function getSubjectSyllabus(codeOrId: string): SyllabusSubject | undefined {
  return ABES_SYLLABUS.find(
    (s) => s.code.toLowerCase() === codeOrId.toLowerCase() || s.id.toLowerCase() === codeOrId.toLowerCase()
  );
}
